<!DOCTYPE html>
<html lang="en">

<title>PS70: Intro to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">


<nav class="navbar navbar-expand-sm navbar-dark" style=" color: #EEE7E8;">
  <div style="align-items: center; justify-content: center;" class="container-fluid">
    <div class="flexrow">
      <h2 class="nav-title">PS70 Fall 2024</h2>
    </div>
    <div class="navbar-nav">
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../about.html">About</a></h4>
    </div>
  </div>
</nav>

<body>
<xmp style="display:none;">
<div class="textcontainer">
<p class="margin">   </p>

<h3>Week 2: 2D Design & Cutting</h3>

<p class="margin">   </p>
<div class="flexrow">
   

   The assignment for this week was to create a box(about the size of a shoebox), follow through another Fusion 360 tutorial and finally measure and model two household items that might be used later for the final project; produce an assemply of these components.
</div>
<p class="margin">   </p>

<h4>Assignment 1: Make a Box</h4>
To start off, here is the mini version of the finger box. This came from the tutorial provided on the course website and I spent time learning how to actually make a finger box. This box had three fingers with 
<br> 
-Length: 100mm 
<br>
-Width: 40mm
<br>
-Height: 40mm
<br>
-Thickness: 4.4mm
<br>
<br> 
<img src="Box Photo 1.jpeg" alt="generic placeholder image">
<br> 
<br> 
<img src="box_unfold.jpeg" alt="generic placeholder image"
>
<br> 
<br> 
BOX FINAL PRODUCT:
This is my final version of my box. My box has seperate panels that were each labeled in Fusion 360 prior to cutting along with a lid to close the box. The template I structured allowed for the number of fingers to change no matter if the box is downsized or resized therefore it can be reusable. Once the box was done in Fusion 360, I went to the laser cutter to cut out each piece of the box. Once cut, each peice was assembled using a hot glue gun and I also added handles to my box for aesthetic and personal comfort in case more things need to be carried. 
<br> 
<br>
User parameters for the box: 
<br> 

<img src="user_parameters.jpeg" alt="generic placeholder image">
<br> 
Here is an image of the box as a whole in Fusion:
<img src="box_project.jpeg" alt="generic placeholder image">
<br>
<br>
This is an image of the bottom panel:
<img src="bottom panel.jpeg" alt="generic placeholder image">
<br>
<br> 
This is an image of the front and back panels(as they are identical):
<img src="left and right panels.jpeg" alt="generic placeholder image">
<br>
<br>
This is an image of the right and left panels(as they are dientical as well):
<img src="right and left panels.jpeg" alt="generic placeholder image">
<br>
This is another image of the box in person:
<br>
<img src="box_name.jpeg" alt="generic placeholder image">
<br>
This is an image of the box with the lid on top:
<br>
<img src="box_with_lid.jpeg" alt="generic placeholder image">
<br>
<br>

<h4>Assignment 2: Fusion 360 Tutorial</h4>
For this next assignment I chose to work through a tutorial on making an ice cube tray. 
<br> 
Here is a link to the tutorial:
<br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/M9LCCwP0tTg?si=jDRzciNPqzZDOUkW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
<br>
FINAL PRODUCT OF ICE CUBE TRAY:
<br>
<img src="ice_tray.jpeg" alt="generic placeholder image">
<br>
<br>
<img src="files_ice_tray.jpeg" alt="generic placeholder image">
<br>
<br>

<h4>Assignment 3: Fusion Modeling</h4>
For this final assingment I chose to model a screwdriver and pliers. 

Measurements were done using calipers: 
<br>
FOR THE SCREWDRIVER:
<br>
Length: 6/12 inches (165.1mm)
<br>
Handle grove length: 158mm
<br>
Base and top width: 1 inch( 25.4mm)
<br>
Shank length: 4 inches(101.6mm)
<br>
Screwdriver tip:
<br>
Length: 6.20mm
<br>
Circumference: 4.5mm
<br> 
<br>
FOR THE PLIERS:
<br>
Plier base(grip handles): 150mm
<br>
Curved handles pertrude out from the circular peice at only 30mm
<br>
Fulcrum:
<br>
Outer circle circumference: 30mm
Inner circle circumference: 12mm
<br>
Cutters:
<br>
Total length(from middle of fulcrum to the edge: 43.284mm
Jaws: 5mm
Total length on the outside: 58.284mm




<br>
Here is the CAD for the screwdriver:
<img src="screwdriver project.jpeg" alt="generic placeholder image">
<br> 
<br> 
<img src="screwdriver_files_fusion.jpeg" alt="generic placeholder image">
<br>
I did watch a video to get a general understanding of where to start: <iframe width="560" height="315" src="https://www.youtube.com/embed/29kCwkapes4?si=LBCWt1LgMlLPaY7I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
<br>
Here is the CAD for the pliers:
<img src="pliers project.jpeg" alt="generic placeholder image">
<br>
<br>
<img src="pliers_files_fusion.jpeg" alt="generic placeholder image">

<br>
The final part of this assignment was to complete an assembly of components. I chose to do an assembly of a screw and a nut that can be used to bolt things together. 
<br>
<img src="screw_nut_assembly.jpeg" alt="generic placeholder image">
<br>
<br>
<img src="screw_nut_files.jpeg" alt="generic placeholder image">







</div>
</xmp>
</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>